spring:
  application:
    name: customer-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:}

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://user:password@cluster.mongodb.net/customer_db?retryWrites=true&w=majority}
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /customer-service
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.liverpool.customer: DEBUG
