server:
  port: ${PORT:8080}
  address: 0.0.0.0
spring:
  forward-headers-strategy: framework
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true

logging:
  level:
    root: INFO
    com.liverpool.customer: INFO
    org.springframework.data.mongodb: WARN
