spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/order_db
      auto-index-creation: true
      # Deshabilitar transacciones para MongoDB standalone (sin replica set)
      transactions:
        enabled: false

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    feign: DEBUG
    com.liverpool.order.infrastructure.adapter.out.client: DEBUG
